INSERT INTO COURSE
(COURSE_NAME, COURSE_DESCRIPTION)
VALUES ('Physics', 'Physics studies');

INSERT INTO TEACHER
(FIRST_NAME, LAST_NAME, TITLE, DESCRIPTION, SOCIAL_MEDIA)
VALUES('James', 'Smith', 'PhD in Physics', 'Physics studies', 'LinkedIn');

INSERT INTO COURSE_TEACHER (COURSE_ID, TEACHER_ID) VALUES (1, 1);

INSERT INTO UNI_GROUP (GROUP_NAME) VALUES ('ff-55');

INSERT INTO ROOM (CAMPUS, ADDRESS, ROOM_NUMBER)
VALUES ('Nathan', 'Kessel Road', 10);

INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, TITLE, DESCRIPTION)
VALUES ('John', 'Wang', 'full time', 'full time description');

INSERT INTO TIMETABLE (DESCRIPTION) VALUES ('some description');

INSERT INTO LESSON (GROUP_ID, ROOM_ID, TEACHER_ID, COURSE_ID, TIMETABLE_ID)
VALUES (1, 1, 1, 1, 1);

INSERT INTO UNI_GROUP (GROUP_NAME) VALUES ('ff-77');

INSERT INTO TIMETABLE (DESCRIPTION) VALUES ('some more description');
