INSERT INTO TEACHER (FIRST_NAME, LAST_NAME, TITLE, DESCRIPTION, SOCIAL_MEDIA)
VALUES ('James', 'Smith', 'PhD in Physics', 'Physics studies', 'LinkedIn');

INSERT INTO TEACHER (FIRST_NAME, LAST_NAME, TITLE, DESCRIPTION, SOCIAL_MEDIA)
VALUES ('Alex', 'Cronin', 'PhD in Mathematics', 'Math studies', 'LinkedIn');

INSERT INTO COURSE (COURSE_NAME, COURSE_DESCRIPTION)
VALUES ('Physics', 'Physics studies');

INSERT INTO COURSE (COURSE_NAME, COURSE_DESCRIPTION)
VALUES ('Mathematics', 'Math studies');

INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, TITLE, DESCRIPTION)
VALUES ('John', 'Wang', 'Full time', 'Full time description');

INSERT INTO STUDENT (FIRST_NAME, LAST_NAME, TITLE, DESCRIPTION)
VALUES ('Mark', 'Maron', 'Full time', 'Full time description');

INSERT INTO UNI_GROUP (GROUP_NAME)
VALUES ('ff-55');

INSERT INTO UNI_GROUP (GROUP_NAME)
VALUES ('mm-77');

INSERT INTO ROOM (CAMPUS, ADDRESS, ROOM_NUMBER)
VALUES ('Nathan', 'Kessel Road', 10);

INSERT INTO ROOM (CAMPUS, ADDRESS, ROOM_NUMBER)
VALUES ('Gold Coast', 'Some Road', 100);

INSERT INTO TIMETABLE (DESCRIPTION)
VALUES ('Some description');

INSERT INTO TIMETABLE (DESCRIPTION)
VALUES ('Some other description');

INSERT INTO COURSE_TEACHER (COURSE_ID, TEACHER_ID)
VALUES (1, 1);

INSERT INTO COURSE_TEACHER (COURSE_ID, TEACHER_ID)
VALUES (2, 2);

UPDATE STUDENT SET GROUP_ID = 1 WHERE STUDENT_ID = 1;

UPDATE STUDENT SET GROUP_ID = 2 WHERE STUDENT_ID = 2;

INSERT INTO COURSE_GROUP (COURSE_ID, GROUP_ID)
VALUES (1, 1);

INSERT INTO COURSE_GROUP (COURSE_ID, GROUP_ID)
VALUES (2, 2);

INSERT INTO LESSON (GROUP_ID, ROOM_ID, TEACHER_ID, COURSE_ID, TIMETABLE_ID)
VALUES (1, 1, 1, 1, 1);

INSERT INTO LESSON (GROUP_ID, ROOM_ID, TEACHER_ID, COURSE_ID, TIMETABLE_ID)
VALUES (2, 2, 2, 2, 2);