CREATE TABLE if not exists COURSE (
COURSE_ID		SERIAL  PRIMARY KEY,
COURSE_NAME		VARCHAR(20)  NOT NULL,
COURSE_DESCRIPTION	VARCHAR(40)
);


CREATE TABLE if not exists UNI_GROUP (
GROUP_ID	SERIAL  PRIMARY KEY,
GROUP_NAME	VARCHAR(20) NOT NULL
);


CREATE TABLE if not exists ROOM (
ROOM_ID		SERIAL            PRIMARY KEY,
CAMPUS		VARCHAR(20)       NOT NULL,
ADDRESS		VARCHAR(40)       NOT NULL,
ROOM_NUMBER	SMALLINT          NOT NULL
);

CREATE TABLE if not exists TIMETABLE (
TIMETABLE_ID		SERIAL  PRIMARY KEY,
DESCRIPTION         VARCHAR(40)
);

CREATE TABLE if not exists STUDENT (
STUDENT_ID	SERIAL PRIMARY KEY,
FIRST_NAME		VARCHAR(20) NOT NULL,
LAST_NAME		VARCHAR(20) NOT NULL,
GROUP_ID	INT,
TITLE		VARCHAR(20) NOT NULL,
DESCRIPTION	VARCHAR(40),
FOREIGN KEY (GROUP_ID) REFERENCES UNI_GROUP (GROUP_ID)
);


CREATE TABLE if not exists TEACHER (
TEACHER_ID	SERIAL PRIMARY KEY,
FIRST_NAME		VARCHAR(20) NOT NULL,
LAST_NAME		VARCHAR(20) NOT NULL,
TITLE		VARCHAR(20) NOT NULL,
DESCRIPTION	VARCHAR(40),
SOCIAL_MEDIA	VARCHAR(20)
);


CREATE TABLE if not exists COURSE_TEACHER (
COURSE_ID		INT,
TEACHER_ID		INT,
FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID),
FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER (TEACHER_ID),
PRIMARY KEY (COURSE_ID, TEACHER_ID)
);


CREATE TABLE if not exists LESSON (
LESSON_ID	SERIAL PRIMARY KEY,
GROUP_ID	INT,
ROOM_ID		INT,
TEACHER_ID	INT,
COURSE_ID	INT,
TIMETABLE_ID INT,
CALENDAR	TIMESTAMP,
FOREIGN KEY (GROUP_ID) REFERENCES UNI_GROUP (GROUP_ID),
FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID),
FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER (TEACHER_ID),
FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID),
FOREIGN KEY (TIMETABLE_ID) REFERENCES TIMETABLE (TIMETABLE_ID)
);


CREATE TABLE if not exists COURSE_GROUP (
COURSE_GROUP_ID	SERIAL PRIMARY KEY,
COURSE_ID		INT,
GROUP_ID		INT,
FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID),
FOREIGN KEY (GROUP_ID) REFERENCES UNI_GROUP (GROUP_ID)
);
